Several changes to clean and speed
[git-p4: depot-paths = "//usr/ryand/Bin/": change = 47]

diff --git a/archdir b/archdir
--- a/archdir
+++ b/archdir
@@ -1,26 +1,26 @@
 #! /bin/csh
 # archdir - tar and compress a directory using tar & gzip
-
+    
 if ($#argv < 1) then		# check num of arguments
-	echo "Usage: $com:t directory..."
-	exit 1
+  echo "Usage: $com:t directory..."
+  exit 1
 endif
 
 # Do all file processing here:
 foreach File ($argv)		# process multiple files
 
-	if ($File == "-help") then	# example of flag
-		echo "PUT HELP HERE"
-		shift			# remove "-help" from queue
-	endif
+  if ($File == "-help") then	# example of flag
+    echo "PUT HELP HERE"
+    shift			# remove "-help" from queue
+  endif
 
-	if (! -d $File) then
-		echo "Error: $File is not a directory"
-		shift
-	endif
+  if (! -d $File) then
+    echo "Error: $File is not a directory"
+    shift
+  endif
 
-	if (-d $File) then
-		(tar cf - $File | gzip -c9 > $File.tar.gz) && /bin/rm -rf $File
-	endif
+  if (-d $File) then
+    ((tar cf - $File | gzip -c9 > $File.tar.gz) && /bin/rm -rf $File) &
+  endif
 end
 
